require('set')
require('keymaps')
-- require('plugs')
require('lazyplugs')
require('plug-config/telescope-config')
require('plug-config/comment-config')
require('plug-config/icons-config')
-- require('plug-config/nx-config')
-- require('theme-config')
require('plug-config/nvimtree-config')
require('plug-config/toggleterm-config')
require('ts-config')
-- require('lsp-config')
require('lspmason-config')
require('plug-config/cmp-config')
