require('keymaps')
require('lazyplugs')
require('plug-config/telescope-config')
-- require('plug-config/nx-config')
-- require('theme-config')
-- require('plug-config/gruvbox-config')
require('plug-config/nvimtree-config')
require('plug-config/toggleterm-config')
-- require('ts-config')
